apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs1
spec:
  replicas: 5
  selector:
    matchLabels:
      type: nginx
  template:
    metadata:
      name: nginx
      labels:
        type: nginx
    spec:
      containers:
      - name: container1
        image: nginx
        ports:
        - containerPort: 5000
          protocol: TCP
